Repository aau-giraf/weekplanner, pull requests merged in 2020-05, with the labels that each got.

#470 Fix pictogram text setting
  lib/screens/settings_screens/settings_screen.dart
  lib/screens/show_activity_screen.dart
  lib/screens/weekplan_screen.dart
  lib/widgets/pictogram_text.dart
  test/blocs/settings_bloc_test.dart
  test/screens/settings_screens/settings_screen_test.dart
  test/screens/show_activity_screen_test.dart
  test/widgets/pictogram_text_test.dart
Labels: Gruppe 11, ReleaseFix

#486 Releasefix - Fixes 469
  lib/blocs/weekplan_bloc.dart
  lib/screens/weekplan_screen.dart
  pubspec.lock
  pubspec.yaml
  test/screens/weekplan_screen_test.dart
Labels: ReleaseFix

#489 Fixes 454
  lib/screens/weekplan_screen.dart
  test/screens/weekplan_screen_test.dart
Labels: Gruppe 16, ReleaseFix

#500 Feature/326 - Added Codecoverage checks and badge
  .github/workflows/main.yml
  .gitignore
  README.md
  codecov.yml
Labels: type: chore

#520 Fix 340
  lib/models/enums/timer_running_mode.dart
  lib/screens/weekplan_screen.dart
  lib/widgets/bottom_app_bar_button_widget.dart
  lib/widgets/weekplan_screen_widgets/activity_card.dart
  lib/widgets/weekplan_screen_widgets/weekplan_day_column.dart
  pubspec.lock
  test/mock_data.dart
  test/screens/weekplan_screen_test.dart
Labels: Gruppe 11

#548 Fixed uploaded picture size in choiceSelector
  lib/widgets/weekplanner_choiceboard_selector.dart
Labels: ReleaseFix

#550 Size of pictograms in ChoiceBoard on weekplan screen are changed
  lib/widgets/weekplan_screen_widgets/activity_card.dart
Labels: ReleaseFix
