Repository aau-giraf/weekplanner, pull requests merged in 2020-03, with the labels that each got.

#313 Update weekplan_screen.dart
  lib/screens/weekplan_screen.dart
Labels: Gruppe 15

#298 Create github actions file
  .github/workflows/main.yml
  ios/Flutter/Debug.xcconfig
  ios/Flutter/Release.xcconfig
  ios/Podfile
  lib/blocs/timer_bloc.dart
  test/blocs/timer_bloc_test.dart
Labels: type: chore

#312 fixes #264
  assets/audio/dingSound.mp3
  lib/blocs/timer_bloc.dart
  pubspec.yaml
Labels: Gruppe 15

#321 Remove azure pipelines in favor of GH Actions
  azure-pipelines.yml
  flutterinstall.sh
Labels: type: chore

#337 fix for issue 319
  lib/blocs/toolbar_bloc.dart
Labels: Gruppe 11

#341 Feature 200
  test/blocs/weekplans_bloc_test.dart
Labels: Gruppe 9

#342 Feature 228
  lib/blocs/toolbar_bloc.dart
  lib/screens/login_screen.dart
  lib/screens/show_activity_screen.dart
  lib/screens/weekplan_screen.dart
  lib/screens/weekplan_selector_screen.dart
  lib/style/custom_color.dart
  lib/widgets/giraf_activity_time_picker_dialog.dart
  lib/widgets/giraf_button_widget.dart
  lib/widgets/giraf_confirm_dialog.dart
  lib/widgets/giraf_copy_activities_dialog.dart
  lib/widgets/giraf_notify_dialog.dart
  lib/widgets/giraf_title_header.dart
  lib/widgets/loading_spinner_widget.dart
Labels: Gruppe 8

#339 fix for issue 207
  lib/blocs/toolbar_bloc.dart
  lib/screens/login_screen.dart
Labels: Gruppe 11

#344 Issue 307
  lib/blocs/timer_bloc.dart
  lib/models/enums/timer_running_mode.dart
  lib/screens/show_activity_screen.dart
  test/blocs/timer_bloc_test.dart
  test/screens/show_activity_screen_test.dart
Labels: Gruppe 8

#354 Fix 309
  lib/blocs/timer_bloc.dart
  lib/screens/show_activity_screen.dart
  test/screens/show_activity_screen_test.dart
Labels: Gruppe 11

#350 fixes_305
  lib/screens/weekplan_selector_screen.dart
  test/screens/weekplan_selector_screen_test.dart
Labels: Gruppe 9

#351 Feature 323 - redesign of settings screen
  .gitignore
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcworkspace/contents.xcworkspacedata
  lib/blocs/toolbar_bloc.dart
  lib/screens/settings_screen.dart
  lib/screens/weekplan_screen.dart
  lib/screens/weekplan_selector_screen.dart
  lib/widgets/settings_widgets/settings_section.dart
  lib/widgets/settings_widgets/settings_section_arrow_button.dart
  lib/widgets/settings_widgets/settings_section_checkboxButton.dart
  lib/widgets/settings_widgets/settings_section_item.dart
  test/screens/settings_screen_test.dart
Labels: Gruppe 14

#368 Fix #228
  lib/blocs/toolbar_bloc.dart
  lib/screens/login_screen.dart
  lib/screens/pictogram_search_screen.dart
  lib/screens/show_activity_screen.dart
  lib/screens/upload_image_from_phone_screen.dart
  lib/screens/weekplan_screen.dart
  lib/screens/weekplan_selector_screen.dart
  lib/style/custom_color.dart
  lib/widgets/giraf_activity_time_picker_dialog.dart
  lib/widgets/giraf_button_widget.dart
  lib/widgets/giraf_confirm_dialog.dart
  lib/widgets/settings_widgets/settings_section.dart
  lib/widgets/settings_widgets/settings_section_arrow_button.dart
  lib/widgets/settings_widgets/settings_section_checkboxButton.dart
Labels: Gruppe 8
