Repository aau-giraf/weekplanner, pull requests merged in 2020-04, with the labels that each got.

#373 Fix 370 : Fixed pictogram scaling
  lib/screens/weekplan_screen.dart
Labels: ReleaseFix

#361 Feature 66
  lib/blocs/new_citizen_bloc.dart
  lib/bootstrap.dart
  lib/screens/choose_citizen_screen.dart
  lib/screens/new_citizen_screen.dart
  test/blocs/new_citizen_bloc_test.dart
  test/screens/choose_citizen_screen_test.dart
  test/screens/new_citizen_screen_test.dart
Labels: Gruppe 15

#422 Feature 64
  lib/screens/settings_screens/color_theme_selection_screen.dart
  lib/screens/settings_screens/settings_screen.dart
  lib/screens/weekplan_screen.dart
  lib/style/standard_week_colors.dart
  lib/widgets/settings_widgets/settings_section.dart
  lib/widgets/settings_widgets/settings_section_arrow_button.dart
  lib/widgets/settings_widgets/settings_section_colorThemeButton.dart
  lib/widgets/settings_widgets/settings_theme_display_box.dart
  test/screens/settings_screens/color_theme_selection_screen_test.dart
  test/screens/settings_screens/settings_screen_test.dart
Labels: Gruppe 11

#424 Feature 348
  lib/screens/weekplan_screen.dart
  lib/widgets/giraf_button_widget.dart
  test/blocs/weekplan_bloc_test.dart
  test/screens/weekplan_screen_test.dart
Labels: Gruppe 9

#421 Feature 65
  lib/screens/settings_screens/color_theme_selection_screen.dart
  lib/screens/settings_screens/completed_activity_icon_selection_screen.dart
  lib/screens/settings_screens/settings_screen.dart
  lib/screens/weekplan_screen.dart
  lib/style/custom_color.dart
  test/screens/settings_screens/settings_screen_test.dart
Labels: Gruppe 8

#440 Feature 376
  lib/blocs/settings_bloc.dart
  lib/screens/settings_screens/number_of_days_selection_screen.dart
  lib/screens/settings_screens/settings_screen.dart
  test/blocs/settings_bloc_test.dart
  test/screens/settings_screens/number_of_days_selection_screen.dart
  test/screens/settings_screens/settings_screen_test.dart
Labels: Gruppe 15

#475 Updated so the errormessages are shown as default.
  lib/screens/new_citizen_screen.dart
Labels: Gruppe 15

#476 Fixes completion mark settings bug
  lib/screens/settings_screens/completed_activity_icon_selection_screen.dart
Labels: Gruppe 8

#466 New ding sound
  assets/audio/dingSound.mp3
  assets/audio/dingSound.wav
  lib/blocs/timer_bloc.dart
Labels: Gruppe 8
