Repository aau-giraf/weekplanner, pull requests merged in 2021-11, with the labels that each got.

#800 Added different enviroments and set it to dev.
  assets/environments.dev.json
  assets/environments.local.json
  assets/environments.tst.json
  lib/main.dart
Labels: GIRAF-1, Sprint 2

#794 Added a trustee enum, and added the use for the role method from the …
  lib/blocs/auth_bloc.dart
  lib/models/enums/weekplan_mode.dart
  lib/screens/upload_image_from_phone_screen.dart
  lib/style/font_size.dart
  pubspec.lock
  test/blocs/auth_bloc.test.dart
Labels: Sprint 1

#735 Feature 648: Rettet grammatiske fejl i weekplanner
  ios/Podfile
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  lib/screens/weekplan_screen.dart
  lib/screens/weekplan_selector_screen.dart
Labels: Sprint 0

#793 Feature 780: Implemented trustee weekplan screen
  lib/blocs/auth_bloc.dart
  lib/models/enums/weekplan_mode.dart
  lib/screens/weekplan_screen.dart
  pubspec.lock
  test/blocs/auth_bloc.test.dart
  test/mock_data.dart
Labels: GIRAF-4, Sprint 1

#801 Feature web api/227: Not able to get the role of a user
  test/blocs/auth_bloc.test.dart
Labels: GIRAF-4, Sprint 2

#817 Bug fix/multiple errors
  lib/blocs/auth_bloc.dart
  lib/screens/login_screen.dart
Labels: Type: bug, GIRAF-4, Sprint 3
